spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postconf
    username: admin
    password: 123456
    hikari:
      poolName: Hikari
      auto-commit: false

server:
  port: 8080

resteasy:
  deployment:
    async_job_service_enabled: true

keycloak:
  server:
    contextPath: /auth
    
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR    
